title:            Elementa
description:      Lightweight and Minimal HTML Microframework
github_url:       http://github.com/dhbmarcos/elementa
donation_address: bc1qnd884sd8jw20uye0y0hwgr40ztslcxavpy7j3a

theme:       null
markdown:    kramdown
highlighter: rouge
plugins:
  - jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
