title: Elementa
description: Lightweight and Minimal HTML Microframework
github_url: https://github.com/usuario/repositorio
donation_address: asd123
# theme: jekyll-theme-cayman
theme: null
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
